// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.apache.flink.pb3.canal.entity;

/**
 * Protobuf type {@code com.alibaba.otter.canal.protocol.CanalEntry}
 */
public final class CanalEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alibaba.otter.canal.protocol.CanalEntry)
    CanalEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CanalEntry.newBuilder() to construct.
  private CanalEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CanalEntry() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CanalEntry();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CanalEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.flink.pb3.canal.entity.CanalEntry.class, org.apache.flink.pb3.canal.entity.CanalEntry.Builder.class);
  }

  public interface EntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.otter.canal.protocol.CanalEntry.Entry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **协议头部信息 *
     * </pre>
     *
     * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <pre>
     **协议头部信息 *
     * </pre>
     *
     * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
     * @return The header.
     */
    org.apache.flink.pb3.canal.entity.Header getHeader();
    /**
     * <pre>
     **协议头部信息 *
     * </pre>
     *
     * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
     */
    org.apache.flink.pb3.canal.entity.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @return Whether the entryType field is set.
     */
    boolean hasEntryType();
    /**
     * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @return The enum numeric value on the wire for entryType.
     */
    int getEntryTypeValue();
    /**
     * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @return The entryType.
     */
    org.apache.flink.pb3.canal.entity.EntryType getEntryType();

    /**
     * <pre>
     **传输的二进制组 *
     * </pre>
     *
     * <code>bytes storeValue = 3;</code>
     * @return The storeValue.
     */
    com.google.protobuf.ByteString getStoreValue();

    public org.apache.flink.pb3.canal.entity.CanalEntry.Entry.EntryTypePresentCase getEntryTypePresentCase();
  }
  /**
   * Protobuf type {@code com.alibaba.otter.canal.protocol.CanalEntry.Entry}
   */
  public static final class Entry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alibaba.otter.canal.protocol.CanalEntry.Entry)
      EntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Entry() {
      storeValue_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Entry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Entry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.apache.flink.pb3.canal.entity.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.apache.flink.pb3.canal.entity.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              entryTypePresentCase_ = 2;
              entryTypePresent_ = rawValue;
              break;
            }
            case 26: {

              storeValue_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.flink.pb3.canal.entity.CanalEntry.Entry.class, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder.class);
    }

    private int bitField0_;
    private int entryTypePresentCase_ = 0;
    private java.lang.Object entryTypePresent_;
    public enum EntryTypePresentCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ENTRYTYPE(2),
      ENTRYTYPEPRESENT_NOT_SET(0);
      private final int value;
      private EntryTypePresentCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EntryTypePresentCase valueOf(int value) {
        return forNumber(value);
      }

      public static EntryTypePresentCase forNumber(int value) {
        switch (value) {
          case 2: return ENTRYTYPE;
          case 0: return ENTRYTYPEPRESENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EntryTypePresentCase
    getEntryTypePresentCase() {
      return EntryTypePresentCase.forNumber(
          entryTypePresentCase_);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private org.apache.flink.pb3.canal.entity.Header header_;
    /**
     * <pre>
     **协议头部信息 *
     * </pre>
     *
     * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     **协议头部信息 *
     * </pre>
     *
     * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.Header getHeader() {
      return header_ == null ? org.apache.flink.pb3.canal.entity.Header.getDefaultInstance() : header_;
    }
    /**
     * <pre>
     **协议头部信息 *
     * </pre>
     *
     * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
     */
    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? org.apache.flink.pb3.canal.entity.Header.getDefaultInstance() : header_;
    }

    public static final int ENTRYTYPE_FIELD_NUMBER = 2;
    /**
     * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @return Whether the entryType field is set.
     */
    public boolean hasEntryType() {
      return entryTypePresentCase_ == 2;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @return The enum numeric value on the wire for entryType.
     */
    public int getEntryTypeValue() {
      if (entryTypePresentCase_ == 2) {
        return (java.lang.Integer) entryTypePresent_;
      }
      return 0;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
     * @return The entryType.
     */
    public org.apache.flink.pb3.canal.entity.EntryType getEntryType() {
      if (entryTypePresentCase_ == 2) {
        @SuppressWarnings("deprecation")
        org.apache.flink.pb3.canal.entity.EntryType result = org.apache.flink.pb3.canal.entity.EntryType.valueOf(
            (java.lang.Integer) entryTypePresent_);
        return result == null ? org.apache.flink.pb3.canal.entity.EntryType.UNRECOGNIZED : result;
      }
      return org.apache.flink.pb3.canal.entity.EntryType.ENTRYTYPECOMPATIBLEPROTO2;
    }

    public static final int STOREVALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString storeValue_;
    /**
     * <pre>
     **传输的二进制组 *
     * </pre>
     *
     * <code>bytes storeValue = 3;</code>
     * @return The storeValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStoreValue() {
      return storeValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      if (entryTypePresentCase_ == 2) {
        output.writeEnum(2, ((java.lang.Integer) entryTypePresent_));
      }
      if (!storeValue_.isEmpty()) {
        output.writeBytes(3, storeValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (entryTypePresentCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, ((java.lang.Integer) entryTypePresent_));
      }
      if (!storeValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, storeValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.flink.pb3.canal.entity.CanalEntry.Entry)) {
        return super.equals(obj);
      }
      org.apache.flink.pb3.canal.entity.CanalEntry.Entry other = (org.apache.flink.pb3.canal.entity.CanalEntry.Entry) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getStoreValue()
          .equals(other.getStoreValue())) return false;
      if (!getEntryTypePresentCase().equals(other.getEntryTypePresentCase())) return false;
      switch (entryTypePresentCase_) {
        case 2:
          if (getEntryTypeValue()
              != other.getEntryTypeValue()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + STOREVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStoreValue().hashCode();
      switch (entryTypePresentCase_) {
        case 2:
          hash = (37 * hash) + ENTRYTYPE_FIELD_NUMBER;
          hash = (53 * hash) + getEntryTypeValue();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.apache.flink.pb3.canal.entity.CanalEntry.Entry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.otter.canal.protocol.CanalEntry.Entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.otter.canal.protocol.CanalEntry.Entry)
        org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.flink.pb3.canal.entity.CanalEntry.Entry.class, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder.class);
      }

      // Construct using org.apache.flink.pb3.canal.entity.CanalEntry.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        storeValue_ = com.google.protobuf.ByteString.EMPTY;

        entryTypePresentCase_ = 0;
        entryTypePresent_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_descriptor;
      }

      @java.lang.Override
      public org.apache.flink.pb3.canal.entity.CanalEntry.Entry getDefaultInstanceForType() {
        return org.apache.flink.pb3.canal.entity.CanalEntry.Entry.getDefaultInstance();
      }

      @java.lang.Override
      public org.apache.flink.pb3.canal.entity.CanalEntry.Entry build() {
        org.apache.flink.pb3.canal.entity.CanalEntry.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.apache.flink.pb3.canal.entity.CanalEntry.Entry buildPartial() {
        org.apache.flink.pb3.canal.entity.CanalEntry.Entry result = new org.apache.flink.pb3.canal.entity.CanalEntry.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (headerBuilder_ == null) {
            result.header_ = header_;
          } else {
            result.header_ = headerBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (entryTypePresentCase_ == 2) {
          result.entryTypePresent_ = entryTypePresent_;
        }
        result.storeValue_ = storeValue_;
        result.bitField0_ = to_bitField0_;
        result.entryTypePresentCase_ = entryTypePresentCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.flink.pb3.canal.entity.CanalEntry.Entry) {
          return mergeFrom((org.apache.flink.pb3.canal.entity.CanalEntry.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.flink.pb3.canal.entity.CanalEntry.Entry other) {
        if (other == org.apache.flink.pb3.canal.entity.CanalEntry.Entry.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getStoreValue() != com.google.protobuf.ByteString.EMPTY) {
          setStoreValue(other.getStoreValue());
        }
        switch (other.getEntryTypePresentCase()) {
          case ENTRYTYPE: {
            setEntryTypeValue(other.getEntryTypeValue());
            break;
          }
          case ENTRYTYPEPRESENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.flink.pb3.canal.entity.CanalEntry.Entry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.flink.pb3.canal.entity.CanalEntry.Entry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int entryTypePresentCase_ = 0;
      private java.lang.Object entryTypePresent_;
      public EntryTypePresentCase
          getEntryTypePresentCase() {
        return EntryTypePresentCase.forNumber(
            entryTypePresentCase_);
      }

      public Builder clearEntryTypePresent() {
        entryTypePresentCase_ = 0;
        entryTypePresent_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private org.apache.flink.pb3.canal.entity.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.apache.flink.pb3.canal.entity.Header, org.apache.flink.pb3.canal.entity.Header.Builder, org.apache.flink.pb3.canal.entity.HeaderOrBuilder> headerBuilder_;
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       * @return The header.
       */
      public org.apache.flink.pb3.canal.entity.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.apache.flink.pb3.canal.entity.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       */
      public Builder setHeader(org.apache.flink.pb3.canal.entity.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       */
      public Builder setHeader(
          org.apache.flink.pb3.canal.entity.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       */
      public Builder mergeHeader(org.apache.flink.pb3.canal.entity.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              header_ != null &&
              header_ != org.apache.flink.pb3.canal.entity.Header.getDefaultInstance()) {
            header_ =
              org.apache.flink.pb3.canal.entity.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       */
      public org.apache.flink.pb3.canal.entity.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       */
      public org.apache.flink.pb3.canal.entity.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.apache.flink.pb3.canal.entity.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <pre>
       **协议头部信息 *
       * </pre>
       *
       * <code>optional .com.alibaba.otter.canal.protocol.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.apache.flink.pb3.canal.entity.Header, org.apache.flink.pb3.canal.entity.Header.Builder, org.apache.flink.pb3.canal.entity.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.apache.flink.pb3.canal.entity.Header, org.apache.flink.pb3.canal.entity.Header.Builder, org.apache.flink.pb3.canal.entity.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      /**
       * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
       * @return Whether the entryType field is set.
       */
      @java.lang.Override
      public boolean hasEntryType() {
        return entryTypePresentCase_ == 2;
      }
      /**
       * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
       * @return The enum numeric value on the wire for entryType.
       */
      @java.lang.Override
      public int getEntryTypeValue() {
        if (entryTypePresentCase_ == 2) {
          return ((java.lang.Integer) entryTypePresent_).intValue();
        }
        return 0;
      }
      /**
       * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
       * @param value The enum numeric value on the wire for entryType to set.
       * @return This builder for chaining.
       */
      public Builder setEntryTypeValue(int value) {
        entryTypePresentCase_ = 2;
        entryTypePresent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
       * @return The entryType.
       */
      @java.lang.Override
      public org.apache.flink.pb3.canal.entity.EntryType getEntryType() {
        if (entryTypePresentCase_ == 2) {
          @SuppressWarnings("deprecation")
          org.apache.flink.pb3.canal.entity.EntryType result = org.apache.flink.pb3.canal.entity.EntryType.valueOf(
              (java.lang.Integer) entryTypePresent_);
          return result == null ? org.apache.flink.pb3.canal.entity.EntryType.UNRECOGNIZED : result;
        }
        return org.apache.flink.pb3.canal.entity.EntryType.ENTRYTYPECOMPATIBLEPROTO2;
      }
      /**
       * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
       * @param value The entryType to set.
       * @return This builder for chaining.
       */
      public Builder setEntryType(org.apache.flink.pb3.canal.entity.EntryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        entryTypePresentCase_ = 2;
        entryTypePresent_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.alibaba.otter.canal.protocol.EntryType entryType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntryType() {
        if (entryTypePresentCase_ == 2) {
          entryTypePresentCase_ = 0;
          entryTypePresent_ = null;
          onChanged();
        }
        return this;
      }

      private com.google.protobuf.ByteString storeValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       **传输的二进制组 *
       * </pre>
       *
       * <code>bytes storeValue = 3;</code>
       * @return The storeValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getStoreValue() {
        return storeValue_;
      }
      /**
       * <pre>
       **传输的二进制组 *
       * </pre>
       *
       * <code>bytes storeValue = 3;</code>
       * @param value The storeValue to set.
       * @return This builder for chaining.
       */
      public Builder setStoreValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        storeValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **传输的二进制组 *
       * </pre>
       *
       * <code>bytes storeValue = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStoreValue() {
        
        storeValue_ = getDefaultInstance().getStoreValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alibaba.otter.canal.protocol.CanalEntry.Entry)
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.otter.canal.protocol.CanalEntry.Entry)
    private static final org.apache.flink.pb3.canal.entity.CanalEntry.Entry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.flink.pb3.canal.entity.CanalEntry.Entry();
    }

    public static org.apache.flink.pb3.canal.entity.CanalEntry.Entry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Entry>
        PARSER = new com.google.protobuf.AbstractParser<Entry>() {
      @java.lang.Override
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Entry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.CanalEntry.Entry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.flink.pb3.canal.entity.CanalEntry)) {
      return super.equals(obj);
    }
    org.apache.flink.pb3.canal.entity.CanalEntry other = (org.apache.flink.pb3.canal.entity.CanalEntry) obj;

    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.pb3.canal.entity.CanalEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.flink.pb3.canal.entity.CanalEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alibaba.otter.canal.protocol.CanalEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alibaba.otter.canal.protocol.CanalEntry)
      org.apache.flink.pb3.canal.entity.CanalEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.flink.pb3.canal.entity.CanalEntry.class, org.apache.flink.pb3.canal.entity.CanalEntry.Builder.class);
    }

    // Construct using org.apache.flink.pb3.canal.entity.CanalEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_CanalEntry_descriptor;
    }

    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.CanalEntry getDefaultInstanceForType() {
      return org.apache.flink.pb3.canal.entity.CanalEntry.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.CanalEntry build() {
      org.apache.flink.pb3.canal.entity.CanalEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.CanalEntry buildPartial() {
      org.apache.flink.pb3.canal.entity.CanalEntry result = new org.apache.flink.pb3.canal.entity.CanalEntry(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.flink.pb3.canal.entity.CanalEntry) {
        return mergeFrom((org.apache.flink.pb3.canal.entity.CanalEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.flink.pb3.canal.entity.CanalEntry other) {
      if (other == org.apache.flink.pb3.canal.entity.CanalEntry.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.apache.flink.pb3.canal.entity.CanalEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.apache.flink.pb3.canal.entity.CanalEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alibaba.otter.canal.protocol.CanalEntry)
  }

  // @@protoc_insertion_point(class_scope:com.alibaba.otter.canal.protocol.CanalEntry)
  private static final org.apache.flink.pb3.canal.entity.CanalEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.flink.pb3.canal.entity.CanalEntry();
  }

  public static org.apache.flink.pb3.canal.entity.CanalEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CanalEntry>
      PARSER = new com.google.protobuf.AbstractParser<CanalEntry>() {
    @java.lang.Override
    public CanalEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CanalEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CanalEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CanalEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.flink.pb3.canal.entity.CanalEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

