// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.apache.flink.pb3.canal.entity;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alibaba.otter.canal.protocol.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   **binlog/redolog文件名 *
   * </pre>
   *
   * <code>string logFileName = 2;</code>
   * @return The logFileName.
   */
  java.lang.String getLogFileName();
  /**
   * <pre>
   **binlog/redolog文件名 *
   * </pre>
   *
   * <code>string logFileName = 2;</code>
   * @return The bytes for logFileName.
   */
  com.google.protobuf.ByteString
      getLogFileNameBytes();

  /**
   * <pre>
   **binlog/redolog文件的偏移位置 *
   * </pre>
   *
   * <code>int64 logFileOffset = 3;</code>
   * @return The logFileOffset.
   */
  long getLogFileOffset();

  /**
   * <pre>
   **服务端serverId *
   * </pre>
   *
   * <code>int64 serverId = 4;</code>
   * @return The serverId.
   */
  long getServerId();

  /**
   * <pre>
   **变更数据的执行编码 *
   * </pre>
   *
   * <code>int64 serverenCode = 5;</code>
   * @return The serverenCode.
   */
  long getServerenCode();

  /**
   * <pre>
   **变更数据的执行时间*
   * </pre>
   *
   * <code>int64 executeTime = 6;</code>
   * @return The executeTime.
   */
  long getExecuteTime();

  /**
   * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
   * @return Whether the sourceType field is set.
   */
  boolean hasSourceType();
  /**
   * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
   * @return The enum numeric value on the wire for sourceType.
   */
  int getSourceTypeValue();
  /**
   * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
   * @return The sourceType.
   */
  org.apache.flink.pb3.canal.entity.Header.Type getSourceType();

  /**
   * <pre>
   **变更数据的schemaname *
   * </pre>
   *
   * <code>string schemaName = 8;</code>
   * @return The schemaName.
   */
  java.lang.String getSchemaName();
  /**
   * <pre>
   **变更数据的schemaname *
   * </pre>
   *
   * <code>string schemaName = 8;</code>
   * @return The bytes for schemaName.
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();

  /**
   * <pre>
   **变更数据的tablename *
   * </pre>
   *
   * <code>string tableName = 9;</code>
   * @return The tableName.
   */
  java.lang.String getTableName();
  /**
   * <pre>
   **变更数据的tablename *
   * </pre>
   *
   * <code>string tableName = 9;</code>
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <pre>
   **传输数据的事件长度*
   * </pre>
   *
   * <code>int64 eventLength = 10;</code>
   * @return The eventLength.
   */
  long getEventLength();

  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
   * @return Whether the eventType field is set.
   */
  boolean hasEventType();
  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
   * @return The eventType.
   */
  org.apache.flink.pb3.canal.entity.EventType getEventType();

  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  java.util.List<org.apache.flink.pb3.canal.entity.Pair> 
      getPropsList();
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  org.apache.flink.pb3.canal.entity.Pair getProps(int index);
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  int getPropsCount();
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  java.util.List<? extends org.apache.flink.pb3.canal.entity.PairOrBuilder> 
      getPropsOrBuilderList();
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  org.apache.flink.pb3.canal.entity.PairOrBuilder getPropsOrBuilder(
      int index);

  /**
   * <pre>
   **当前事务的gitd*
   * </pre>
   *
   * <code>string gtid = 13;</code>
   * @return The gtid.
   */
  java.lang.String getGtid();
  /**
   * <pre>
   **当前事务的gitd*
   * </pre>
   *
   * <code>string gtid = 13;</code>
   * @return The bytes for gtid.
   */
  com.google.protobuf.ByteString
      getGtidBytes();

  public org.apache.flink.pb3.canal.entity.Header.VersionPresentCase getVersionPresentCase();

  public org.apache.flink.pb3.canal.entity.Header.SourceTypePresentCase getSourceTypePresentCase();

  public org.apache.flink.pb3.canal.entity.Header.EventTypePresentCase getEventTypePresentCase();
}
