// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.apache.flink.pb3.canal.entity;

/**
 * <pre>
 *还原出的canal消息格式
 * </pre>
 *
 * Protobuf type {@code com.alibaba.otter.canal.protocol.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alibaba.otter.canal.protocol.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    entries_ = java.util.Collections.emptyList();
    rawEntries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              entries_ = new java.util.ArrayList<org.apache.flink.pb3.canal.entity.CanalEntry.Entry>();
              mutable_bitField0_ |= 0x00000001;
            }
            entries_.add(
                input.readMessage(org.apache.flink.pb3.canal.entity.CanalEntry.Entry.parser(), extensionRegistry));
            break;
          }
          case 24: {

            raw_ = input.readBool();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              rawEntries_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000002;
            }
            rawEntries_.add(input.readBytes());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        entries_ = java.util.Collections.unmodifiableList(entries_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        rawEntries_ = java.util.Collections.unmodifiableList(rawEntries_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.flink.pb3.canal.entity.Message.class, org.apache.flink.pb3.canal.entity.Message.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 2;
  private java.util.List<org.apache.flink.pb3.canal.entity.CanalEntry.Entry> entries_;
  /**
   * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.apache.flink.pb3.canal.entity.CanalEntry.Entry> getEntriesList() {
    return entries_;
  }
  /**
   * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
   */
  @java.lang.Override
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
   */
  @java.lang.Override
  public org.apache.flink.pb3.canal.entity.CanalEntry.Entry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
   */
  @java.lang.Override
  public org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }

  public static final int RAW_FIELD_NUMBER = 3;
  private boolean raw_;
  /**
   * <code>bool raw = 3;</code>
   * @return The raw.
   */
  @java.lang.Override
  public boolean getRaw() {
    return raw_;
  }

  public static final int RAWENTRIES_FIELD_NUMBER = 4;
  private java.util.List<com.google.protobuf.ByteString> rawEntries_;
  /**
   * <code>repeated bytes rawEntries = 4;</code>
   * @return A list containing the rawEntries.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getRawEntriesList() {
    return rawEntries_;
  }
  /**
   * <code>repeated bytes rawEntries = 4;</code>
   * @return The count of rawEntries.
   */
  public int getRawEntriesCount() {
    return rawEntries_.size();
  }
  /**
   * <code>repeated bytes rawEntries = 4;</code>
   * @param index The index of the element to return.
   * @return The rawEntries at the given index.
   */
  public com.google.protobuf.ByteString getRawEntries(int index) {
    return rawEntries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      output.writeMessage(2, entries_.get(i));
    }
    if (raw_ != false) {
      output.writeBool(3, raw_);
    }
    for (int i = 0; i < rawEntries_.size(); i++) {
      output.writeBytes(4, rawEntries_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, entries_.get(i));
    }
    if (raw_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, raw_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < rawEntries_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(rawEntries_.get(i));
      }
      size += dataSize;
      size += 1 * getRawEntriesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.flink.pb3.canal.entity.Message)) {
      return super.equals(obj);
    }
    org.apache.flink.pb3.canal.entity.Message other = (org.apache.flink.pb3.canal.entity.Message) obj;

    if (getId()
        != other.getId()) return false;
    if (!getEntriesList()
        .equals(other.getEntriesList())) return false;
    if (getRaw()
        != other.getRaw()) return false;
    if (!getRawEntriesList()
        .equals(other.getRawEntriesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (37 * hash) + RAW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRaw());
    if (getRawEntriesCount() > 0) {
      hash = (37 * hash) + RAWENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getRawEntriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.flink.pb3.canal.entity.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.flink.pb3.canal.entity.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *还原出的canal消息格式
   * </pre>
   *
   * Protobuf type {@code com.alibaba.otter.canal.protocol.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alibaba.otter.canal.protocol.Message)
      org.apache.flink.pb3.canal.entity.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.flink.pb3.canal.entity.Message.class, org.apache.flink.pb3.canal.entity.Message.Builder.class);
    }

    // Construct using org.apache.flink.pb3.canal.entity.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        entriesBuilder_.clear();
      }
      raw_ = false;

      rawEntries_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.flink.pb3.canal.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Message_descriptor;
    }

    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.Message getDefaultInstanceForType() {
      return org.apache.flink.pb3.canal.entity.Message.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.Message build() {
      org.apache.flink.pb3.canal.entity.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.flink.pb3.canal.entity.Message buildPartial() {
      org.apache.flink.pb3.canal.entity.Message result = new org.apache.flink.pb3.canal.entity.Message(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (entriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entries_ = entries_;
      } else {
        result.entries_ = entriesBuilder_.build();
      }
      result.raw_ = raw_;
      if (((bitField0_ & 0x00000002) != 0)) {
        rawEntries_ = java.util.Collections.unmodifiableList(rawEntries_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.rawEntries_ = rawEntries_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.flink.pb3.canal.entity.Message) {
        return mergeFrom((org.apache.flink.pb3.canal.entity.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.flink.pb3.canal.entity.Message other) {
      if (other == org.apache.flink.pb3.canal.entity.Message.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (entriesBuilder_ == null) {
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
      } else {
        if (!other.entries_.isEmpty()) {
          if (entriesBuilder_.isEmpty()) {
            entriesBuilder_.dispose();
            entriesBuilder_ = null;
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntriesFieldBuilder() : null;
          } else {
            entriesBuilder_.addAllMessages(other.entries_);
          }
        }
      }
      if (other.getRaw() != false) {
        setRaw(other.getRaw());
      }
      if (!other.rawEntries_.isEmpty()) {
        if (rawEntries_.isEmpty()) {
          rawEntries_ = other.rawEntries_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRawEntriesIsMutable();
          rawEntries_.addAll(other.rawEntries_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.apache.flink.pb3.canal.entity.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.apache.flink.pb3.canal.entity.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.apache.flink.pb3.canal.entity.CanalEntry.Entry> entries_ =
      java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entries_ = new java.util.ArrayList<org.apache.flink.pb3.canal.entity.CanalEntry.Entry>(entries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.flink.pb3.canal.entity.CanalEntry.Entry, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder, org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder> entriesBuilder_;

    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public java.util.List<org.apache.flink.pb3.canal.entity.CanalEntry.Entry> getEntriesList() {
      if (entriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entries_);
      } else {
        return entriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public int getEntriesCount() {
      if (entriesBuilder_ == null) {
        return entries_.size();
      } else {
        return entriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public org.apache.flink.pb3.canal.entity.CanalEntry.Entry getEntries(int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);
      } else {
        return entriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder setEntries(
        int index, org.apache.flink.pb3.canal.entity.CanalEntry.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder setEntries(
        int index, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.set(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder addEntries(org.apache.flink.pb3.canal.entity.CanalEntry.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder addEntries(
        int index, org.apache.flink.pb3.canal.entity.CanalEntry.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(index, value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder addEntries(
        org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder addEntries(
        int index, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends org.apache.flink.pb3.canal.entity.CanalEntry.Entry> values) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
      } else {
        entriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder clearEntries() {
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public Builder removeEntries(int index) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.remove(index);
        onChanged();
      } else {
        entriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder getEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder getEntriesOrBuilder(
        int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);  } else {
        return entriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public java.util.List<? extends org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder> 
         getEntriesOrBuilderList() {
      if (entriesBuilder_ != null) {
        return entriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries_);
      }
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder addEntriesBuilder() {
      return getEntriesFieldBuilder().addBuilder(
          org.apache.flink.pb3.canal.entity.CanalEntry.Entry.getDefaultInstance());
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder addEntriesBuilder(
        int index) {
      return getEntriesFieldBuilder().addBuilder(
          index, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.getDefaultInstance());
    }
    /**
     * <code>repeated .com.alibaba.otter.canal.protocol.CanalEntry.Entry entries = 2;</code>
     */
    public java.util.List<org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder> 
         getEntriesBuilderList() {
      return getEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.apache.flink.pb3.canal.entity.CanalEntry.Entry, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder, org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder> 
        getEntriesFieldBuilder() {
      if (entriesBuilder_ == null) {
        entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.apache.flink.pb3.canal.entity.CanalEntry.Entry, org.apache.flink.pb3.canal.entity.CanalEntry.Entry.Builder, org.apache.flink.pb3.canal.entity.CanalEntry.EntryOrBuilder>(
                entries_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entries_ = null;
      }
      return entriesBuilder_;
    }

    private boolean raw_ ;
    /**
     * <code>bool raw = 3;</code>
     * @return The raw.
     */
    @java.lang.Override
    public boolean getRaw() {
      return raw_;
    }
    /**
     * <code>bool raw = 3;</code>
     * @param value The raw to set.
     * @return This builder for chaining.
     */
    public Builder setRaw(boolean value) {
      
      raw_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool raw = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRaw() {
      
      raw_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> rawEntries_ = java.util.Collections.emptyList();
    private void ensureRawEntriesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rawEntries_ = new java.util.ArrayList<com.google.protobuf.ByteString>(rawEntries_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated bytes rawEntries = 4;</code>
     * @return A list containing the rawEntries.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getRawEntriesList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(rawEntries_) : rawEntries_;
    }
    /**
     * <code>repeated bytes rawEntries = 4;</code>
     * @return The count of rawEntries.
     */
    public int getRawEntriesCount() {
      return rawEntries_.size();
    }
    /**
     * <code>repeated bytes rawEntries = 4;</code>
     * @param index The index of the element to return.
     * @return The rawEntries at the given index.
     */
    public com.google.protobuf.ByteString getRawEntries(int index) {
      return rawEntries_.get(index);
    }
    /**
     * <code>repeated bytes rawEntries = 4;</code>
     * @param index The index to set the value at.
     * @param value The rawEntries to set.
     * @return This builder for chaining.
     */
    public Builder setRawEntries(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRawEntriesIsMutable();
      rawEntries_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes rawEntries = 4;</code>
     * @param value The rawEntries to add.
     * @return This builder for chaining.
     */
    public Builder addRawEntries(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRawEntriesIsMutable();
      rawEntries_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes rawEntries = 4;</code>
     * @param values The rawEntries to add.
     * @return This builder for chaining.
     */
    public Builder addAllRawEntries(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureRawEntriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, rawEntries_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes rawEntries = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRawEntries() {
      rawEntries_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alibaba.otter.canal.protocol.Message)
  }

  // @@protoc_insertion_point(class_scope:com.alibaba.otter.canal.protocol.Message)
  private static final org.apache.flink.pb3.canal.entity.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.flink.pb3.canal.entity.Message();
  }

  public static org.apache.flink.pb3.canal.entity.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.flink.pb3.canal.entity.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

