// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.apache.flink.pb3.canal.entity;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_CanalEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_CanalEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_Column_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_Column_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_RowData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_RowData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_RowChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_RowChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_Pair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_Pair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_otter_canal_protocol_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_otter_canal_protocol_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022 com.alibaba.otter.canal" +
      ".protocol\"{\n\007Message\022\n\n\002id\030\001 \001(\003\022C\n\007entr" +
      "ies\030\002 \003(\01322.com.alibaba.otter.canal.prot" +
      "ocol.CanalEntry.Entry\022\013\n\003raw\030\003 \001(\010\022\022\n\nra" +
      "wEntries\030\004 \003(\014\"\313\001\n\nCanalEntry\032\274\001\n\005Entry\022" +
      "=\n\006header\030\001 \001(\0132(.com.alibaba.otter.cana" +
      "l.protocol.HeaderH\001\210\001\001\022@\n\tentryType\030\002 \001(" +
      "\0162+.com.alibaba.otter.canal.protocol.Ent" +
      "ryTypeH\000\022\022\n\nstoreValue\030\003 \001(\014B\023\n\021entryTyp" +
      "e_presentB\t\n\007_header\"6\n\006Column\022\r\n\005index\030" +
      "\001 \001(\005\022\017\n\007sqlType\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\"\300\001\n" +
      "\007RowData\022>\n\014afterColumns\030\002 \003(\0132(.com.ali" +
      "baba.otter.canal.protocol.Column\022?\n\rbefo" +
      "reColumns\030\001 \003(\0132(.com.alibaba.otter.cana" +
      "l.protocol.Column\0224\n\004pros\030\003 \003(\0132&.com.al" +
      "ibaba.otter.canal.protocol.Pair\"s\n\tRowCh" +
      "ange\022\017\n\007tableId\030\001 \001(\003\022@\n\teventType\030\002 \001(\016" +
      "2+.com.alibaba.otter.canal.protocol.Even" +
      "tTypeH\000B\023\n\021eventType_present\"\"\n\004Pair\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\216\004\n\006Header\022\021\n\007v" +
      "ersion\030\001 \001(\005H\000\022\023\n\013logFileName\030\002 \001(\t\022\025\n\rl" +
      "ogFileOffset\030\003 \001(\003\022\020\n\010serverId\030\004 \001(\003\022\024\n\014" +
      "serverenCode\030\005 \001(\003\022\023\n\013executeTime\030\006 \001(\003\022" +
      "C\n\nsourceType\030\007 \001(\0162-.com.alibaba.otter." +
      "canal.protocol.Header.TypeH\001\022\022\n\nschemaNa" +
      "me\030\010 \001(\t\022\021\n\ttableName\030\t \001(\t\022\023\n\013eventLeng" +
      "th\030\n \001(\003\022@\n\teventType\030\013 \001(\0162+.com.alibab" +
      "a.otter.canal.protocol.EventTypeH\002\0225\n\005pr" +
      "ops\030\014 \003(\0132&.com.alibaba.otter.canal.prot" +
      "ocol.Pair\022\014\n\004gtid\030\r \001(\t\"B\n\004Type\022\030\n\024TYPEC" +
      "OMPATIBLEPROTO2\020\000\022\n\n\006ORACLE\020\001\022\t\n\005MYSQL\020\002" +
      "\022\t\n\005PGSQL\020\003B\021\n\017version_presentB\024\n\022source" +
      "Type_presentB\023\n\021eventType_present*\345\001\n\tEv" +
      "entType\022\035\n\031EVENTTYPECOMPATIBLEPROTO2\020\000\022\n" +
      "\n\006INSERT\020\001\022\n\n\006UPDATE\020\002\022\n\n\006DELETE\020\003\022\n\n\006CR" +
      "EATE\020\004\022\t\n\005ALTER\020\005\022\t\n\005ERASE\020\006\022\t\n\005QUERY\020\007\022" +
      "\014\n\010TRUNCATE\020\010\022\n\n\006RENAME\020\t\022\n\n\006CINDEX\020\n\022\n\n" +
      "\006DINDEX\020\013\022\010\n\004GTID\020\014\022\014\n\010XACOMMIT\020\r\022\016\n\nXAR" +
      "OLLBACK\020\016\022\016\n\nMHEARTBEAT\020\017*}\n\tEntryType\022\035" +
      "\n\031ENTRYTYPECOMPATIBLEPROTO2\020\000\022\024\n\020TRANSAC" +
      "TIONBEGIN\020\001\022\013\n\007ROWDATA\020\002\022\022\n\016TRANSACTIONE" +
      "ND\020\003\022\r\n\tHEARTBEAT\020\004\022\013\n\007GTIDLOG\020\005B*\n!org." +
      "apache.flink.pb3.canal.entityH\001P\001\200\001\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_alibaba_otter_canal_protocol_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alibaba_otter_canal_protocol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_Message_descriptor,
        new java.lang.String[] { "Id", "Entries", "Raw", "RawEntries", });
    internal_static_com_alibaba_otter_canal_protocol_CanalEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alibaba_otter_canal_protocol_CanalEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_CanalEntry_descriptor,
        new java.lang.String[] { });
    internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_descriptor =
      internal_static_com_alibaba_otter_canal_protocol_CanalEntry_descriptor.getNestedTypes().get(0);
    internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_CanalEntry_Entry_descriptor,
        new java.lang.String[] { "Header", "EntryType", "StoreValue", "EntryTypePresent", "Header", });
    internal_static_com_alibaba_otter_canal_protocol_Column_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_alibaba_otter_canal_protocol_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_Column_descriptor,
        new java.lang.String[] { "Index", "SqlType", "Name", });
    internal_static_com_alibaba_otter_canal_protocol_RowData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_alibaba_otter_canal_protocol_RowData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_RowData_descriptor,
        new java.lang.String[] { "AfterColumns", "BeforeColumns", "Pros", });
    internal_static_com_alibaba_otter_canal_protocol_RowChange_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_alibaba_otter_canal_protocol_RowChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_RowChange_descriptor,
        new java.lang.String[] { "TableId", "EventType", "EventTypePresent", });
    internal_static_com_alibaba_otter_canal_protocol_Pair_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_alibaba_otter_canal_protocol_Pair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_Pair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_alibaba_otter_canal_protocol_Header_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_alibaba_otter_canal_protocol_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_otter_canal_protocol_Header_descriptor,
        new java.lang.String[] { "Version", "LogFileName", "LogFileOffset", "ServerId", "ServerenCode", "ExecuteTime", "SourceType", "SchemaName", "TableName", "EventLength", "EventType", "Props", "Gtid", "VersionPresent", "SourceTypePresent", "EventTypePresent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
