// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.apache.flink.pb3.canal.entity;

public interface RowDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alibaba.otter.canal.protocol.RowData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  java.util.List<org.apache.flink.pb3.canal.entity.Column> 
      getAfterColumnsList();
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  org.apache.flink.pb3.canal.entity.Column getAfterColumns(int index);
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  int getAfterColumnsCount();
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  java.util.List<? extends org.apache.flink.pb3.canal.entity.ColumnOrBuilder> 
      getAfterColumnsOrBuilderList();
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  org.apache.flink.pb3.canal.entity.ColumnOrBuilder getAfterColumnsOrBuilder(
      int index);

  /**
   * <pre>
   **changelog insert,delete,*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  java.util.List<org.apache.flink.pb3.canal.entity.Column> 
      getBeforeColumnsList();
  /**
   * <pre>
   **changelog insert,delete,*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  org.apache.flink.pb3.canal.entity.Column getBeforeColumns(int index);
  /**
   * <pre>
   **changelog insert,delete,*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  int getBeforeColumnsCount();
  /**
   * <pre>
   **changelog insert,delete,*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  java.util.List<? extends org.apache.flink.pb3.canal.entity.ColumnOrBuilder> 
      getBeforeColumnsOrBuilderList();
  /**
   * <pre>
   **changelog insert,delete,*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  org.apache.flink.pb3.canal.entity.ColumnOrBuilder getBeforeColumnsOrBuilder(
      int index);

  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  java.util.List<org.apache.flink.pb3.canal.entity.Pair> 
      getProsList();
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  org.apache.flink.pb3.canal.entity.Pair getPros(int index);
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  int getProsCount();
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  java.util.List<? extends org.apache.flink.pb3.canal.entity.PairOrBuilder> 
      getProsOrBuilderList();
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  org.apache.flink.pb3.canal.entity.PairOrBuilder getProsOrBuilder(
      int index);
}
