// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.alibaba.otter.canal.protocol.entity;

/**
 * Protobuf type {@code com.alibaba.otter.canal.protocol.Header}
 */
public final class Header extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alibaba.otter.canal.protocol.Header)
    HeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Header.newBuilder() to construct.
  private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Header() {
    logFileName_ = "";
    schemaName_ = "";
    tableName_ = "";
    props_ = java.util.Collections.emptyList();
    gtid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Header();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Header(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            versionPresentCase_ = 1;
            versionPresent_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            logFileName_ = s;
            break;
          }
          case 24: {

            logFileOffset_ = input.readInt64();
            break;
          }
          case 32: {

            serverId_ = input.readInt64();
            break;
          }
          case 40: {

            serverenCode_ = input.readInt64();
            break;
          }
          case 48: {

            executeTime_ = input.readInt64();
            break;
          }
          case 56: {
            int rawValue = input.readEnum();
            sourceTypePresentCase_ = 7;
            sourceTypePresent_ = rawValue;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            schemaName_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 80: {

            eventLength_ = input.readInt64();
            break;
          }
          case 88: {
            int rawValue = input.readEnum();
            eventTypePresentCase_ = 11;
            eventTypePresent_ = rawValue;
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              props_ = new java.util.ArrayList<com.alibaba.otter.canal.protocol.entity.Pair>();
              mutable_bitField0_ |= 0x00000001;
            }
            props_.add(
                input.readMessage(com.alibaba.otter.canal.protocol.entity.Pair.parser(), extensionRegistry));
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            gtid_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        props_ = java.util.Collections.unmodifiableList(props_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alibaba.otter.canal.protocol.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Header_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alibaba.otter.canal.protocol.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Header_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alibaba.otter.canal.protocol.entity.Header.class, com.alibaba.otter.canal.protocol.entity.Header.Builder.class);
  }

  /**
   * <pre>
   **上游需要监听的数据源类型 *
   * </pre>
   *
   * Protobuf enum {@code com.alibaba.otter.canal.protocol.Header.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TYPECOMPATIBLEPROTO2 = 0;</code>
     */
    TYPECOMPATIBLEPROTO2(0),
    /**
     * <code>ORACLE = 1;</code>
     */
    ORACLE(1),
    /**
     * <code>MYSQL = 2;</code>
     */
    MYSQL(2),
    /**
     * <code>PGSQL = 3;</code>
     */
    PGSQL(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TYPECOMPATIBLEPROTO2 = 0;</code>
     */
    public static final int TYPECOMPATIBLEPROTO2_VALUE = 0;
    /**
     * <code>ORACLE = 1;</code>
     */
    public static final int ORACLE_VALUE = 1;
    /**
     * <code>MYSQL = 2;</code>
     */
    public static final int MYSQL_VALUE = 2;
    /**
     * <code>PGSQL = 3;</code>
     */
    public static final int PGSQL_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return TYPECOMPATIBLEPROTO2;
        case 1: return ORACLE;
        case 2: return MYSQL;
        case 3: return PGSQL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.alibaba.otter.canal.protocol.entity.Header.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.alibaba.otter.canal.protocol.Header.Type)
  }

  private int versionPresentCase_ = 0;
  private java.lang.Object versionPresent_;
  public enum VersionPresentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    VERSION(1),
    VERSIONPRESENT_NOT_SET(0);
    private final int value;
    private VersionPresentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VersionPresentCase valueOf(int value) {
      return forNumber(value);
    }

    public static VersionPresentCase forNumber(int value) {
      switch (value) {
        case 1: return VERSION;
        case 0: return VERSIONPRESENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public VersionPresentCase
  getVersionPresentCase() {
    return VersionPresentCase.forNumber(
        versionPresentCase_);
  }

  private int sourceTypePresentCase_ = 0;
  private java.lang.Object sourceTypePresent_;
  public enum SourceTypePresentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SOURCETYPE(7),
    SOURCETYPEPRESENT_NOT_SET(0);
    private final int value;
    private SourceTypePresentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SourceTypePresentCase valueOf(int value) {
      return forNumber(value);
    }

    public static SourceTypePresentCase forNumber(int value) {
      switch (value) {
        case 7: return SOURCETYPE;
        case 0: return SOURCETYPEPRESENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SourceTypePresentCase
  getSourceTypePresentCase() {
    return SourceTypePresentCase.forNumber(
        sourceTypePresentCase_);
  }

  private int eventTypePresentCase_ = 0;
  private java.lang.Object eventTypePresent_;
  public enum EventTypePresentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    EVENTTYPE(11),
    EVENTTYPEPRESENT_NOT_SET(0);
    private final int value;
    private EventTypePresentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventTypePresentCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventTypePresentCase forNumber(int value) {
      switch (value) {
        case 11: return EVENTTYPE;
        case 0: return EVENTTYPEPRESENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventTypePresentCase
  getEventTypePresentCase() {
    return EventTypePresentCase.forNumber(
        eventTypePresentCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  /**
   * <code>int32 version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return versionPresentCase_ == 1;
  }
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    if (versionPresentCase_ == 1) {
      return (java.lang.Integer) versionPresent_;
    }
    return 0;
  }

  public static final int LOGFILENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object logFileName_;
  /**
   * <pre>
   **binlog/redolog文件名 *
   * </pre>
   *
   * <code>string logFileName = 2;</code>
   * @return The logFileName.
   */
  @java.lang.Override
  public java.lang.String getLogFileName() {
    java.lang.Object ref = logFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logFileName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **binlog/redolog文件名 *
   * </pre>
   *
   * <code>string logFileName = 2;</code>
   * @return The bytes for logFileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogFileNameBytes() {
    java.lang.Object ref = logFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGFILEOFFSET_FIELD_NUMBER = 3;
  private long logFileOffset_;
  /**
   * <pre>
   **binlog/redolog文件的偏移位置 *
   * </pre>
   *
   * <code>int64 logFileOffset = 3;</code>
   * @return The logFileOffset.
   */
  @java.lang.Override
  public long getLogFileOffset() {
    return logFileOffset_;
  }

  public static final int SERVERID_FIELD_NUMBER = 4;
  private long serverId_;
  /**
   * <pre>
   **服务端serverId *
   * </pre>
   *
   * <code>int64 serverId = 4;</code>
   * @return The serverId.
   */
  @java.lang.Override
  public long getServerId() {
    return serverId_;
  }

  public static final int SERVERENCODE_FIELD_NUMBER = 5;
  private long serverenCode_;
  /**
   * <pre>
   **变更数据的执行编码 *
   * </pre>
   *
   * <code>int64 serverenCode = 5;</code>
   * @return The serverenCode.
   */
  @java.lang.Override
  public long getServerenCode() {
    return serverenCode_;
  }

  public static final int EXECUTETIME_FIELD_NUMBER = 6;
  private long executeTime_;
  /**
   * <pre>
   **变更数据的执行时间*
   * </pre>
   *
   * <code>int64 executeTime = 6;</code>
   * @return The executeTime.
   */
  @java.lang.Override
  public long getExecuteTime() {
    return executeTime_;
  }

  public static final int SOURCETYPE_FIELD_NUMBER = 7;
  /**
   * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
   * @return Whether the sourceType field is set.
   */
  public boolean hasSourceType() {
    return sourceTypePresentCase_ == 7;
  }
  /**
   * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
   * @return The enum numeric value on the wire for sourceType.
   */
  public int getSourceTypeValue() {
    if (sourceTypePresentCase_ == 7) {
      return (java.lang.Integer) sourceTypePresent_;
    }
    return 0;
  }
  /**
   * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
   * @return The sourceType.
   */
  public com.alibaba.otter.canal.protocol.entity.Header.Type getSourceType() {
    if (sourceTypePresentCase_ == 7) {
      @SuppressWarnings("deprecation")
      com.alibaba.otter.canal.protocol.entity.Header.Type result = com.alibaba.otter.canal.protocol.entity.Header.Type.valueOf(
          (java.lang.Integer) sourceTypePresent_);
      return result == null ? com.alibaba.otter.canal.protocol.entity.Header.Type.UNRECOGNIZED : result;
    }
    return com.alibaba.otter.canal.protocol.entity.Header.Type.TYPECOMPATIBLEPROTO2;
  }

  public static final int SCHEMANAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object schemaName_;
  /**
   * <pre>
   **变更数据的schemaname *
   * </pre>
   *
   * <code>string schemaName = 8;</code>
   * @return The schemaName.
   */
  @java.lang.Override
  public java.lang.String getSchemaName() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schemaName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **变更数据的schemaname *
   * </pre>
   *
   * <code>string schemaName = 8;</code>
   * @return The bytes for schemaName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemaNameBytes() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schemaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLENAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object tableName_;
  /**
   * <pre>
   **变更数据的tablename *
   * </pre>
   *
   * <code>string tableName = 9;</code>
   * @return The tableName.
   */
  @java.lang.Override
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **变更数据的tablename *
   * </pre>
   *
   * <code>string tableName = 9;</code>
   * @return The bytes for tableName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENTLENGTH_FIELD_NUMBER = 10;
  private long eventLength_;
  /**
   * <pre>
   **传输数据的事件长度*
   * </pre>
   *
   * <code>int64 eventLength = 10;</code>
   * @return The eventLength.
   */
  @java.lang.Override
  public long getEventLength() {
    return eventLength_;
  }

  public static final int EVENTTYPE_FIELD_NUMBER = 11;
  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
   * @return Whether the eventType field is set.
   */
  public boolean hasEventType() {
    return eventTypePresentCase_ == 11;
  }
  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  public int getEventTypeValue() {
    if (eventTypePresentCase_ == 11) {
      return (java.lang.Integer) eventTypePresent_;
    }
    return 0;
  }
  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
   * @return The eventType.
   */
  public com.alibaba.otter.canal.protocol.entity.EventType getEventType() {
    if (eventTypePresentCase_ == 11) {
      @SuppressWarnings("deprecation")
      com.alibaba.otter.canal.protocol.entity.EventType result = com.alibaba.otter.canal.protocol.entity.EventType.valueOf(
          (java.lang.Integer) eventTypePresent_);
      return result == null ? com.alibaba.otter.canal.protocol.entity.EventType.UNRECOGNIZED : result;
    }
    return com.alibaba.otter.canal.protocol.entity.EventType.EVENTTYPECOMPATIBLEPROTO2;
  }

  public static final int PROPS_FIELD_NUMBER = 12;
  private java.util.List<com.alibaba.otter.canal.protocol.entity.Pair> props_;
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  @java.lang.Override
  public java.util.List<com.alibaba.otter.canal.protocol.entity.Pair> getPropsList() {
    return props_;
  }
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.alibaba.otter.canal.protocol.entity.PairOrBuilder> 
      getPropsOrBuilderList() {
    return props_;
  }
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  @java.lang.Override
  public int getPropsCount() {
    return props_.size();
  }
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  @java.lang.Override
  public com.alibaba.otter.canal.protocol.entity.Pair getProps(int index) {
    return props_.get(index);
  }
  /**
   * <pre>
   **预留扩展*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
   */
  @java.lang.Override
  public com.alibaba.otter.canal.protocol.entity.PairOrBuilder getPropsOrBuilder(
      int index) {
    return props_.get(index);
  }

  public static final int GTID_FIELD_NUMBER = 13;
  private volatile java.lang.Object gtid_;
  /**
   * <pre>
   **当前事务的gitd*
   * </pre>
   *
   * <code>string gtid = 13;</code>
   * @return The gtid.
   */
  @java.lang.Override
  public java.lang.String getGtid() {
    java.lang.Object ref = gtid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gtid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **当前事务的gitd*
   * </pre>
   *
   * <code>string gtid = 13;</code>
   * @return The bytes for gtid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGtidBytes() {
    java.lang.Object ref = gtid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gtid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (versionPresentCase_ == 1) {
      output.writeInt32(
          1, (int)((java.lang.Integer) versionPresent_));
    }
    if (!getLogFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, logFileName_);
    }
    if (logFileOffset_ != 0L) {
      output.writeInt64(3, logFileOffset_);
    }
    if (serverId_ != 0L) {
      output.writeInt64(4, serverId_);
    }
    if (serverenCode_ != 0L) {
      output.writeInt64(5, serverenCode_);
    }
    if (executeTime_ != 0L) {
      output.writeInt64(6, executeTime_);
    }
    if (sourceTypePresentCase_ == 7) {
      output.writeEnum(7, ((java.lang.Integer) sourceTypePresent_));
    }
    if (!getSchemaNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, schemaName_);
    }
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, tableName_);
    }
    if (eventLength_ != 0L) {
      output.writeInt64(10, eventLength_);
    }
    if (eventTypePresentCase_ == 11) {
      output.writeEnum(11, ((java.lang.Integer) eventTypePresent_));
    }
    for (int i = 0; i < props_.size(); i++) {
      output.writeMessage(12, props_.get(i));
    }
    if (!getGtidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, gtid_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (versionPresentCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            1, (int)((java.lang.Integer) versionPresent_));
    }
    if (!getLogFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, logFileName_);
    }
    if (logFileOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, logFileOffset_);
    }
    if (serverId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, serverId_);
    }
    if (serverenCode_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, serverenCode_);
    }
    if (executeTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, executeTime_);
    }
    if (sourceTypePresentCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, ((java.lang.Integer) sourceTypePresent_));
    }
    if (!getSchemaNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, schemaName_);
    }
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, tableName_);
    }
    if (eventLength_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, eventLength_);
    }
    if (eventTypePresentCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, ((java.lang.Integer) eventTypePresent_));
    }
    for (int i = 0; i < props_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, props_.get(i));
    }
    if (!getGtidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, gtid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alibaba.otter.canal.protocol.entity.Header)) {
      return super.equals(obj);
    }
    com.alibaba.otter.canal.protocol.entity.Header other = (com.alibaba.otter.canal.protocol.entity.Header) obj;

    if (!getLogFileName()
        .equals(other.getLogFileName())) return false;
    if (getLogFileOffset()
        != other.getLogFileOffset()) return false;
    if (getServerId()
        != other.getServerId()) return false;
    if (getServerenCode()
        != other.getServerenCode()) return false;
    if (getExecuteTime()
        != other.getExecuteTime()) return false;
    if (!getSchemaName()
        .equals(other.getSchemaName())) return false;
    if (!getTableName()
        .equals(other.getTableName())) return false;
    if (getEventLength()
        != other.getEventLength()) return false;
    if (!getPropsList()
        .equals(other.getPropsList())) return false;
    if (!getGtid()
        .equals(other.getGtid())) return false;
    if (!getVersionPresentCase().equals(other.getVersionPresentCase())) return false;
    switch (versionPresentCase_) {
      case 1:
        if (getVersion()
            != other.getVersion()) return false;
        break;
      case 0:
      default:
    }
    if (!getSourceTypePresentCase().equals(other.getSourceTypePresentCase())) return false;
    switch (sourceTypePresentCase_) {
      case 7:
        if (getSourceTypeValue()
            != other.getSourceTypeValue()) return false;
        break;
      case 0:
      default:
    }
    if (!getEventTypePresentCase().equals(other.getEventTypePresentCase())) return false;
    switch (eventTypePresentCase_) {
      case 11:
        if (getEventTypeValue()
            != other.getEventTypeValue()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOGFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getLogFileName().hashCode();
    hash = (37 * hash) + LOGFILEOFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLogFileOffset());
    hash = (37 * hash) + SERVERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getServerId());
    hash = (37 * hash) + SERVERENCODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getServerenCode());
    hash = (37 * hash) + EXECUTETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecuteTime());
    hash = (37 * hash) + SCHEMANAME_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaName().hashCode();
    hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + EVENTLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEventLength());
    if (getPropsCount() > 0) {
      hash = (37 * hash) + PROPS_FIELD_NUMBER;
      hash = (53 * hash) + getPropsList().hashCode();
    }
    hash = (37 * hash) + GTID_FIELD_NUMBER;
    hash = (53 * hash) + getGtid().hashCode();
    switch (versionPresentCase_) {
      case 1:
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
        break;
      case 0:
      default:
    }
    switch (sourceTypePresentCase_) {
      case 7:
        hash = (37 * hash) + SOURCETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSourceTypeValue();
        break;
      case 0:
      default:
    }
    switch (eventTypePresentCase_) {
      case 11:
        hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getEventTypeValue();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.otter.canal.protocol.entity.Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alibaba.otter.canal.protocol.entity.Header prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alibaba.otter.canal.protocol.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alibaba.otter.canal.protocol.Header)
      com.alibaba.otter.canal.protocol.entity.HeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.otter.canal.protocol.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.otter.canal.protocol.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.otter.canal.protocol.entity.Header.class, com.alibaba.otter.canal.protocol.entity.Header.Builder.class);
    }

    // Construct using com.alibaba.otter.canal.protocol.entity.Header.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPropsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      logFileName_ = "";

      logFileOffset_ = 0L;

      serverId_ = 0L;

      serverenCode_ = 0L;

      executeTime_ = 0L;

      schemaName_ = "";

      tableName_ = "";

      eventLength_ = 0L;

      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        propsBuilder_.clear();
      }
      gtid_ = "";

      versionPresentCase_ = 0;
      versionPresent_ = null;
      sourceTypePresentCase_ = 0;
      sourceTypePresent_ = null;
      eventTypePresentCase_ = 0;
      eventTypePresent_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alibaba.otter.canal.protocol.entity.MessageOuterClass.internal_static_com_alibaba_otter_canal_protocol_Header_descriptor;
    }

    @java.lang.Override
    public com.alibaba.otter.canal.protocol.entity.Header getDefaultInstanceForType() {
      return com.alibaba.otter.canal.protocol.entity.Header.getDefaultInstance();
    }

    @java.lang.Override
    public com.alibaba.otter.canal.protocol.entity.Header build() {
      com.alibaba.otter.canal.protocol.entity.Header result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alibaba.otter.canal.protocol.entity.Header buildPartial() {
      com.alibaba.otter.canal.protocol.entity.Header result = new com.alibaba.otter.canal.protocol.entity.Header(this);
      int from_bitField0_ = bitField0_;
      if (versionPresentCase_ == 1) {
        result.versionPresent_ = versionPresent_;
      }
      result.logFileName_ = logFileName_;
      result.logFileOffset_ = logFileOffset_;
      result.serverId_ = serverId_;
      result.serverenCode_ = serverenCode_;
      result.executeTime_ = executeTime_;
      if (sourceTypePresentCase_ == 7) {
        result.sourceTypePresent_ = sourceTypePresent_;
      }
      result.schemaName_ = schemaName_;
      result.tableName_ = tableName_;
      result.eventLength_ = eventLength_;
      if (eventTypePresentCase_ == 11) {
        result.eventTypePresent_ = eventTypePresent_;
      }
      if (propsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          props_ = java.util.Collections.unmodifiableList(props_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.props_ = props_;
      } else {
        result.props_ = propsBuilder_.build();
      }
      result.gtid_ = gtid_;
      result.versionPresentCase_ = versionPresentCase_;
      result.sourceTypePresentCase_ = sourceTypePresentCase_;
      result.eventTypePresentCase_ = eventTypePresentCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alibaba.otter.canal.protocol.entity.Header) {
        return mergeFrom((com.alibaba.otter.canal.protocol.entity.Header)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alibaba.otter.canal.protocol.entity.Header other) {
      if (other == com.alibaba.otter.canal.protocol.entity.Header.getDefaultInstance()) return this;
      if (!other.getLogFileName().isEmpty()) {
        logFileName_ = other.logFileName_;
        onChanged();
      }
      if (other.getLogFileOffset() != 0L) {
        setLogFileOffset(other.getLogFileOffset());
      }
      if (other.getServerId() != 0L) {
        setServerId(other.getServerId());
      }
      if (other.getServerenCode() != 0L) {
        setServerenCode(other.getServerenCode());
      }
      if (other.getExecuteTime() != 0L) {
        setExecuteTime(other.getExecuteTime());
      }
      if (!other.getSchemaName().isEmpty()) {
        schemaName_ = other.schemaName_;
        onChanged();
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (other.getEventLength() != 0L) {
        setEventLength(other.getEventLength());
      }
      if (propsBuilder_ == null) {
        if (!other.props_.isEmpty()) {
          if (props_.isEmpty()) {
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePropsIsMutable();
            props_.addAll(other.props_);
          }
          onChanged();
        }
      } else {
        if (!other.props_.isEmpty()) {
          if (propsBuilder_.isEmpty()) {
            propsBuilder_.dispose();
            propsBuilder_ = null;
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
            propsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPropsFieldBuilder() : null;
          } else {
            propsBuilder_.addAllMessages(other.props_);
          }
        }
      }
      if (!other.getGtid().isEmpty()) {
        gtid_ = other.gtid_;
        onChanged();
      }
      switch (other.getVersionPresentCase()) {
        case VERSION: {
          setVersion(other.getVersion());
          break;
        }
        case VERSIONPRESENT_NOT_SET: {
          break;
        }
      }
      switch (other.getSourceTypePresentCase()) {
        case SOURCETYPE: {
          setSourceTypeValue(other.getSourceTypeValue());
          break;
        }
        case SOURCETYPEPRESENT_NOT_SET: {
          break;
        }
      }
      switch (other.getEventTypePresentCase()) {
        case EVENTTYPE: {
          setEventTypeValue(other.getEventTypeValue());
          break;
        }
        case EVENTTYPEPRESENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alibaba.otter.canal.protocol.entity.Header parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alibaba.otter.canal.protocol.entity.Header) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int versionPresentCase_ = 0;
    private java.lang.Object versionPresent_;
    public VersionPresentCase
        getVersionPresentCase() {
      return VersionPresentCase.forNumber(
          versionPresentCase_);
    }

    public Builder clearVersionPresent() {
      versionPresentCase_ = 0;
      versionPresent_ = null;
      onChanged();
      return this;
    }

    private int sourceTypePresentCase_ = 0;
    private java.lang.Object sourceTypePresent_;
    public SourceTypePresentCase
        getSourceTypePresentCase() {
      return SourceTypePresentCase.forNumber(
          sourceTypePresentCase_);
    }

    public Builder clearSourceTypePresent() {
      sourceTypePresentCase_ = 0;
      sourceTypePresent_ = null;
      onChanged();
      return this;
    }

    private int eventTypePresentCase_ = 0;
    private java.lang.Object eventTypePresent_;
    public EventTypePresentCase
        getEventTypePresentCase() {
      return EventTypePresentCase.forNumber(
          eventTypePresentCase_);
    }

    public Builder clearEventTypePresent() {
      eventTypePresentCase_ = 0;
      eventTypePresent_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return versionPresentCase_ == 1;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    public int getVersion() {
      if (versionPresentCase_ == 1) {
        return (java.lang.Integer) versionPresent_;
      }
      return 0;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      versionPresentCase_ = 1;
      versionPresent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      if (versionPresentCase_ == 1) {
        versionPresentCase_ = 0;
        versionPresent_ = null;
        onChanged();
      }
      return this;
    }

    private java.lang.Object logFileName_ = "";
    /**
     * <pre>
     **binlog/redolog文件名 *
     * </pre>
     *
     * <code>string logFileName = 2;</code>
     * @return The logFileName.
     */
    public java.lang.String getLogFileName() {
      java.lang.Object ref = logFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **binlog/redolog文件名 *
     * </pre>
     *
     * <code>string logFileName = 2;</code>
     * @return The bytes for logFileName.
     */
    public com.google.protobuf.ByteString
        getLogFileNameBytes() {
      java.lang.Object ref = logFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **binlog/redolog文件名 *
     * </pre>
     *
     * <code>string logFileName = 2;</code>
     * @param value The logFileName to set.
     * @return This builder for chaining.
     */
    public Builder setLogFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      logFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **binlog/redolog文件名 *
     * </pre>
     *
     * <code>string logFileName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogFileName() {
      
      logFileName_ = getDefaultInstance().getLogFileName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **binlog/redolog文件名 *
     * </pre>
     *
     * <code>string logFileName = 2;</code>
     * @param value The bytes for logFileName to set.
     * @return This builder for chaining.
     */
    public Builder setLogFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      logFileName_ = value;
      onChanged();
      return this;
    }

    private long logFileOffset_ ;
    /**
     * <pre>
     **binlog/redolog文件的偏移位置 *
     * </pre>
     *
     * <code>int64 logFileOffset = 3;</code>
     * @return The logFileOffset.
     */
    @java.lang.Override
    public long getLogFileOffset() {
      return logFileOffset_;
    }
    /**
     * <pre>
     **binlog/redolog文件的偏移位置 *
     * </pre>
     *
     * <code>int64 logFileOffset = 3;</code>
     * @param value The logFileOffset to set.
     * @return This builder for chaining.
     */
    public Builder setLogFileOffset(long value) {
      
      logFileOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **binlog/redolog文件的偏移位置 *
     * </pre>
     *
     * <code>int64 logFileOffset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogFileOffset() {
      
      logFileOffset_ = 0L;
      onChanged();
      return this;
    }

    private long serverId_ ;
    /**
     * <pre>
     **服务端serverId *
     * </pre>
     *
     * <code>int64 serverId = 4;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public long getServerId() {
      return serverId_;
    }
    /**
     * <pre>
     **服务端serverId *
     * </pre>
     *
     * <code>int64 serverId = 4;</code>
     * @param value The serverId to set.
     * @return This builder for chaining.
     */
    public Builder setServerId(long value) {
      
      serverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **服务端serverId *
     * </pre>
     *
     * <code>int64 serverId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerId() {
      
      serverId_ = 0L;
      onChanged();
      return this;
    }

    private long serverenCode_ ;
    /**
     * <pre>
     **变更数据的执行编码 *
     * </pre>
     *
     * <code>int64 serverenCode = 5;</code>
     * @return The serverenCode.
     */
    @java.lang.Override
    public long getServerenCode() {
      return serverenCode_;
    }
    /**
     * <pre>
     **变更数据的执行编码 *
     * </pre>
     *
     * <code>int64 serverenCode = 5;</code>
     * @param value The serverenCode to set.
     * @return This builder for chaining.
     */
    public Builder setServerenCode(long value) {
      
      serverenCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **变更数据的执行编码 *
     * </pre>
     *
     * <code>int64 serverenCode = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerenCode() {
      
      serverenCode_ = 0L;
      onChanged();
      return this;
    }

    private long executeTime_ ;
    /**
     * <pre>
     **变更数据的执行时间*
     * </pre>
     *
     * <code>int64 executeTime = 6;</code>
     * @return The executeTime.
     */
    @java.lang.Override
    public long getExecuteTime() {
      return executeTime_;
    }
    /**
     * <pre>
     **变更数据的执行时间*
     * </pre>
     *
     * <code>int64 executeTime = 6;</code>
     * @param value The executeTime to set.
     * @return This builder for chaining.
     */
    public Builder setExecuteTime(long value) {
      
      executeTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **变更数据的执行时间*
     * </pre>
     *
     * <code>int64 executeTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecuteTime() {
      
      executeTime_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
     * @return Whether the sourceType field is set.
     */
    @java.lang.Override
    public boolean hasSourceType() {
      return sourceTypePresentCase_ == 7;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
     * @return The enum numeric value on the wire for sourceType.
     */
    @java.lang.Override
    public int getSourceTypeValue() {
      if (sourceTypePresentCase_ == 7) {
        return ((java.lang.Integer) sourceTypePresent_).intValue();
      }
      return 0;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
     * @param value The enum numeric value on the wire for sourceType to set.
     * @return This builder for chaining.
     */
    public Builder setSourceTypeValue(int value) {
      sourceTypePresentCase_ = 7;
      sourceTypePresent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
     * @return The sourceType.
     */
    @java.lang.Override
    public com.alibaba.otter.canal.protocol.entity.Header.Type getSourceType() {
      if (sourceTypePresentCase_ == 7) {
        @SuppressWarnings("deprecation")
        com.alibaba.otter.canal.protocol.entity.Header.Type result = com.alibaba.otter.canal.protocol.entity.Header.Type.valueOf(
            (java.lang.Integer) sourceTypePresent_);
        return result == null ? com.alibaba.otter.canal.protocol.entity.Header.Type.UNRECOGNIZED : result;
      }
      return com.alibaba.otter.canal.protocol.entity.Header.Type.TYPECOMPATIBLEPROTO2;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
     * @param value The sourceType to set.
     * @return This builder for chaining.
     */
    public Builder setSourceType(com.alibaba.otter.canal.protocol.entity.Header.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      sourceTypePresentCase_ = 7;
      sourceTypePresent_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.Header.Type sourceType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceType() {
      if (sourceTypePresentCase_ == 7) {
        sourceTypePresentCase_ = 0;
        sourceTypePresent_ = null;
        onChanged();
      }
      return this;
    }

    private java.lang.Object schemaName_ = "";
    /**
     * <pre>
     **变更数据的schemaname *
     * </pre>
     *
     * <code>string schemaName = 8;</code>
     * @return The schemaName.
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **变更数据的schemaname *
     * </pre>
     *
     * <code>string schemaName = 8;</code>
     * @return The bytes for schemaName.
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **变更数据的schemaname *
     * </pre>
     *
     * <code>string schemaName = 8;</code>
     * @param value The schemaName to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schemaName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **变更数据的schemaname *
     * </pre>
     *
     * <code>string schemaName = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaName() {
      
      schemaName_ = getDefaultInstance().getSchemaName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **变更数据的schemaname *
     * </pre>
     *
     * <code>string schemaName = 8;</code>
     * @param value The bytes for schemaName to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schemaName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <pre>
     **变更数据的tablename *
     * </pre>
     *
     * <code>string tableName = 9;</code>
     * @return The tableName.
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **变更数据的tablename *
     * </pre>
     *
     * <code>string tableName = 9;</code>
     * @return The bytes for tableName.
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **变更数据的tablename *
     * </pre>
     *
     * <code>string tableName = 9;</code>
     * @param value The tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **变更数据的tablename *
     * </pre>
     *
     * <code>string tableName = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **变更数据的tablename *
     * </pre>
     *
     * <code>string tableName = 9;</code>
     * @param value The bytes for tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private long eventLength_ ;
    /**
     * <pre>
     **传输数据的事件长度*
     * </pre>
     *
     * <code>int64 eventLength = 10;</code>
     * @return The eventLength.
     */
    @java.lang.Override
    public long getEventLength() {
      return eventLength_;
    }
    /**
     * <pre>
     **传输数据的事件长度*
     * </pre>
     *
     * <code>int64 eventLength = 10;</code>
     * @param value The eventLength to set.
     * @return This builder for chaining.
     */
    public Builder setEventLength(long value) {
      
      eventLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **传输数据的事件长度*
     * </pre>
     *
     * <code>int64 eventLength = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventLength() {
      
      eventLength_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @return Whether the eventType field is set.
     */
    @java.lang.Override
    public boolean hasEventType() {
      return eventTypePresentCase_ == 11;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override
    public int getEventTypeValue() {
      if (eventTypePresentCase_ == 11) {
        return ((java.lang.Integer) eventTypePresent_).intValue();
      }
      return 0;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      eventTypePresentCase_ = 11;
      eventTypePresent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public com.alibaba.otter.canal.protocol.entity.EventType getEventType() {
      if (eventTypePresentCase_ == 11) {
        @SuppressWarnings("deprecation")
        com.alibaba.otter.canal.protocol.entity.EventType result = com.alibaba.otter.canal.protocol.entity.EventType.valueOf(
            (java.lang.Integer) eventTypePresent_);
        return result == null ? com.alibaba.otter.canal.protocol.entity.EventType.UNRECOGNIZED : result;
      }
      return com.alibaba.otter.canal.protocol.entity.EventType.EVENTTYPECOMPATIBLEPROTO2;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(com.alibaba.otter.canal.protocol.entity.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      eventTypePresentCase_ = 11;
      eventTypePresent_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      if (eventTypePresentCase_ == 11) {
        eventTypePresentCase_ = 0;
        eventTypePresent_ = null;
        onChanged();
      }
      return this;
    }

    private java.util.List<com.alibaba.otter.canal.protocol.entity.Pair> props_ =
      java.util.Collections.emptyList();
    private void ensurePropsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        props_ = new java.util.ArrayList<com.alibaba.otter.canal.protocol.entity.Pair>(props_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.alibaba.otter.canal.protocol.entity.Pair, com.alibaba.otter.canal.protocol.entity.Pair.Builder, com.alibaba.otter.canal.protocol.entity.PairOrBuilder> propsBuilder_;

    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public java.util.List<com.alibaba.otter.canal.protocol.entity.Pair> getPropsList() {
      if (propsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(props_);
      } else {
        return propsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public int getPropsCount() {
      if (propsBuilder_ == null) {
        return props_.size();
      } else {
        return propsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public com.alibaba.otter.canal.protocol.entity.Pair getProps(int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);
      } else {
        return propsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder setProps(
        int index, com.alibaba.otter.canal.protocol.entity.Pair value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.set(index, value);
        onChanged();
      } else {
        propsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder setProps(
        int index, com.alibaba.otter.canal.protocol.entity.Pair.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.set(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder addProps(com.alibaba.otter.canal.protocol.entity.Pair value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(value);
        onChanged();
      } else {
        propsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder addProps(
        int index, com.alibaba.otter.canal.protocol.entity.Pair value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(index, value);
        onChanged();
      } else {
        propsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder addProps(
        com.alibaba.otter.canal.protocol.entity.Pair.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder addProps(
        int index, com.alibaba.otter.canal.protocol.entity.Pair.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder addAllProps(
        java.lang.Iterable<? extends com.alibaba.otter.canal.protocol.entity.Pair> values) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, props_);
        onChanged();
      } else {
        propsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder clearProps() {
      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        propsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public Builder removeProps(int index) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.remove(index);
        onChanged();
      } else {
        propsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public com.alibaba.otter.canal.protocol.entity.Pair.Builder getPropsBuilder(
        int index) {
      return getPropsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public com.alibaba.otter.canal.protocol.entity.PairOrBuilder getPropsOrBuilder(
        int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);  } else {
        return propsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public java.util.List<? extends com.alibaba.otter.canal.protocol.entity.PairOrBuilder> 
         getPropsOrBuilderList() {
      if (propsBuilder_ != null) {
        return propsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(props_);
      }
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public com.alibaba.otter.canal.protocol.entity.Pair.Builder addPropsBuilder() {
      return getPropsFieldBuilder().addBuilder(
          com.alibaba.otter.canal.protocol.entity.Pair.getDefaultInstance());
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public com.alibaba.otter.canal.protocol.entity.Pair.Builder addPropsBuilder(
        int index) {
      return getPropsFieldBuilder().addBuilder(
          index, com.alibaba.otter.canal.protocol.entity.Pair.getDefaultInstance());
    }
    /**
     * <pre>
     **预留扩展*
     * </pre>
     *
     * <code>repeated .com.alibaba.otter.canal.protocol.Pair props = 12;</code>
     */
    public java.util.List<com.alibaba.otter.canal.protocol.entity.Pair.Builder> 
         getPropsBuilderList() {
      return getPropsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.alibaba.otter.canal.protocol.entity.Pair, com.alibaba.otter.canal.protocol.entity.Pair.Builder, com.alibaba.otter.canal.protocol.entity.PairOrBuilder> 
        getPropsFieldBuilder() {
      if (propsBuilder_ == null) {
        propsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.alibaba.otter.canal.protocol.entity.Pair, com.alibaba.otter.canal.protocol.entity.Pair.Builder, com.alibaba.otter.canal.protocol.entity.PairOrBuilder>(
                props_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        props_ = null;
      }
      return propsBuilder_;
    }

    private java.lang.Object gtid_ = "";
    /**
     * <pre>
     **当前事务的gitd*
     * </pre>
     *
     * <code>string gtid = 13;</code>
     * @return The gtid.
     */
    public java.lang.String getGtid() {
      java.lang.Object ref = gtid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gtid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **当前事务的gitd*
     * </pre>
     *
     * <code>string gtid = 13;</code>
     * @return The bytes for gtid.
     */
    public com.google.protobuf.ByteString
        getGtidBytes() {
      java.lang.Object ref = gtid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gtid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **当前事务的gitd*
     * </pre>
     *
     * <code>string gtid = 13;</code>
     * @param value The gtid to set.
     * @return This builder for chaining.
     */
    public Builder setGtid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gtid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **当前事务的gitd*
     * </pre>
     *
     * <code>string gtid = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearGtid() {
      
      gtid_ = getDefaultInstance().getGtid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **当前事务的gitd*
     * </pre>
     *
     * <code>string gtid = 13;</code>
     * @param value The bytes for gtid to set.
     * @return This builder for chaining.
     */
    public Builder setGtidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gtid_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alibaba.otter.canal.protocol.Header)
  }

  // @@protoc_insertion_point(class_scope:com.alibaba.otter.canal.protocol.Header)
  private static final com.alibaba.otter.canal.protocol.entity.Header DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alibaba.otter.canal.protocol.entity.Header();
  }

  public static com.alibaba.otter.canal.protocol.entity.Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Header>
      PARSER = new com.google.protobuf.AbstractParser<Header>() {
    @java.lang.Override
    public Header parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Header(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Header> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Header> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alibaba.otter.canal.protocol.entity.Header getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

