// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.alibaba.otter.canal.protocol.entity;

public interface RowChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alibaba.otter.canal.protocol.RowChange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **tableId,由数据库产生 *
   * </pre>
   *
   * <code>int64 tableId = 1;</code>
   * @return The tableId.
   */
  long getTableId();

  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 2;</code>
   * @return Whether the eventType field is set.
   */
  boolean hasEventType();
  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 2;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.com.alibaba.otter.canal.protocol.EventType eventType = 2;</code>
   * @return The eventType.
   */
  com.alibaba.otter.canal.protocol.entity.EventType getEventType();

  public com.alibaba.otter.canal.protocol.entity.RowChange.EventTypePresentCase getEventTypePresentCase();
}
