// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.alibaba.otter.canal.protocol.entity;

public interface RowDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alibaba.otter.canal.protocol.RowData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **字段信息，增量数据(修改前，删除前)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  java.util.List<com.alibaba.otter.canal.protocol.entity.Column> 
      getBeforeColumnsList();
  /**
   * <pre>
   **字段信息，增量数据(修改前，删除前)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  com.alibaba.otter.canal.protocol.entity.Column getBeforeColumns(int index);
  /**
   * <pre>
   **字段信息，增量数据(修改前，删除前)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  int getBeforeColumnsCount();
  /**
   * <pre>
   **字段信息，增量数据(修改前，删除前)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  java.util.List<? extends com.alibaba.otter.canal.protocol.entity.ColumnOrBuilder> 
      getBeforeColumnsOrBuilderList();
  /**
   * <pre>
   **字段信息，增量数据(修改前，删除前)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column beforeColumns = 1;</code>
   */
  com.alibaba.otter.canal.protocol.entity.ColumnOrBuilder getBeforeColumnsOrBuilder(
      int index);

  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  java.util.List<com.alibaba.otter.canal.protocol.entity.Column> 
      getAfterColumnsList();
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  com.alibaba.otter.canal.protocol.entity.Column getAfterColumns(int index);
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  int getAfterColumnsCount();
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  java.util.List<? extends com.alibaba.otter.canal.protocol.entity.ColumnOrBuilder> 
      getAfterColumnsOrBuilderList();
  /**
   * <pre>
   **字段信息，增量数据(修改后，新增后)*
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Column afterColumns = 2;</code>
   */
  com.alibaba.otter.canal.protocol.entity.ColumnOrBuilder getAfterColumnsOrBuilder(
      int index);

  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  java.util.List<com.alibaba.otter.canal.protocol.entity.Pair> 
      getProsList();
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  com.alibaba.otter.canal.protocol.entity.Pair getPros(int index);
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  int getProsCount();
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  java.util.List<? extends com.alibaba.otter.canal.protocol.entity.PairOrBuilder> 
      getProsOrBuilderList();
  /**
   * <pre>
   **预留拓展 *
   * </pre>
   *
   * <code>repeated .com.alibaba.otter.canal.protocol.Pair pros = 3;</code>
   */
  com.alibaba.otter.canal.protocol.entity.PairOrBuilder getProsOrBuilder(
      int index);
}
