// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_test.proto

package org.apache.flink;

public final class MapTestOuterClass {
  private MapTestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apache_flink_MapTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apache_flink_MapTest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_apache_flink_MapTest_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_apache_flink_MapTest_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016map_test.proto\022\020com.apache.flink\"\220\001\n\007M" +
      "apTest\022\030\n\013test_string\030\001 \001(\tH\000\210\001\001\022/\n\003map\030" +
      "\002 \003(\0132\".com.apache.flink.MapTest.MapEntr" +
      "y\032*\n\010MapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001B\016\n\014_test_stringB\024\n\020org.apache.flin" +
      "kP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_apache_flink_MapTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_apache_flink_MapTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apache_flink_MapTest_descriptor,
        new java.lang.String[] { "TestString", "Map", "TestString", });
    internal_static_com_apache_flink_MapTest_MapEntry_descriptor =
      internal_static_com_apache_flink_MapTest_descriptor.getNestedTypes().get(0);
    internal_static_com_apache_flink_MapTest_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_apache_flink_MapTest_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
