// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_test.proto

package org.apache.flink;

public interface MapTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.apache.flink.MapTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string test_string = 1;</code>
   * @return Whether the testString field is set.
   */
  boolean hasTestString();
  /**
   * <code>optional string test_string = 1;</code>
   * @return The testString.
   */
  java.lang.String getTestString();
  /**
   * <code>optional string test_string = 1;</code>
   * @return The bytes for testString.
   */
  com.google.protobuf.ByteString
      getTestStringBytes();

  /**
   * <code>map&lt;string, string&gt; map = 2;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, string&gt; map = 2;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMap();
  /**
   * <code>map&lt;string, string&gt; map = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMapMap();
  /**
   * <code>map&lt;string, string&gt; map = 2;</code>
   */

  java.lang.String getMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; map = 2;</code>
   */

  java.lang.String getMapOrThrow(
      java.lang.String key);
}
